# -*- coding: utf-8 -*-
"""capstone2_YOLOv5_training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qv3Agfor9g-Wr9IBXVIWDyTN3Zl0HBtw
"""

from google.colab import drive # Google Colab의 drive 모듈을 임포트(import)
drive.mount('/content/gdrive') # Google 드라이브를 /content/gdrive 디렉토리에 마운트함

import torch #PyTorch 라이브러리를 임포트
from IPython.display import Image #IPython의 display 모듈에서 Image 클래스를 임포트

# Commented out IPython magic to ensure Python compatibility.
# 현재 작업 디렉토리를 /yolov5로 변경
# %cd /content/gdrive/MyDrive/

# GitHub 저장소에서 YOLOv5 코드를 클론(clone)하기
!git clone https://github.com/ultralytics/yolov5

# 자기 위치 확인하는 명령어
!pwd

# Commented out IPython magic to ensure Python compatibility.
# YOLOv5 파일 안으로 들어가는 코드
# %cd /content/gdrive/MyDrive/yolov5
!pwd

# YOLOv5 모델이 정상적으로 동작하기 위해 필요한 모든 Python 패키지 설치
!pip install -r requirements.txt

# warning이라고 경고 나오면 그냥 취소 누르기

# 뭔지 모르겠는데 아마 필요할듯?

from tqdm import tqdm # tqdm 모듈에서 tqdm 클래스를 임포트
from ipywidgets import IntProgress # ipywidgets 모듈에서 IntProgress 클래스를 임포트





"""**이 코드 이하부터 데이터 학습 시작**"""

# 학습 시작
!python train.py --img 416 --batch 16 --epochs 100 --data /content/gdrive/MyDrive/yolov5/data/dataset.yaml --weights yolov5s.pt --cache


# 맨 아래에 결과로 Results saved to runs/train/exp9 이렇게 쓰여져있음



# 검사
!python detect.py --weights /content/gdrive/MyDrive/yolov5/runs/train/exp12/weights/best.pt --img 416 --conf 0.25 --source /content/gdrive/MyDrive/yolov5/data/train/bird_1.jpg

# .tflite안드에는 무거운걸 다룰 수 없어서 가볍게 만들어주는 것.
# .pt는 무거운거 .tflite는 가벼운 것

# !!!!!! --weights 뒤에 모델 넣어주기!(경로 잘 보기)
!python export.py --weights /content/gdrive/MyDrive/yolov5/runs/train/exp12/weights/best.pt --include tflite --img 416

# 검사 // 앞에는 검사할 모델 뒤에는 검사할 사진(source)


!python detect.py --weights /content/gdrive/MyDrive/yolov5/runs/train/exp12/weights/best-fp16.tflite --img 416 --conf 0.01 --source /content/gdrive/MyDrive/yolov5/data/train/tum_test_img_03.jpg

